abstract: A Meta Object Protocol for Perl 5
author: Stevan Little <stevan@iinteractive.com>
build_requires: 
  File::Spec: 0
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Class-MOP
no_index: 
  directory: 
    - inc
    - t
requires: 
  B: 0
  Carp: 0
  Scalar::Util: 1.18
  Sub::Name: 0.02
version: 0.46
