---
abstract: 'A Meta Object Protocol for Perl 5'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::Exception: 0.27
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-MOP
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Carp: 0
  Devel::GlobalDestruction: 0
  MRO::Compat: 0.05
  Scalar::Util: 1.18
  Sub::Name: 0.04
  Task::Weaken: 0
  Try::Tiny: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.98
