---
name: Class-MOP
version: 0.37_002
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
  - 'Yuval Kogman E<lt>nothingmuch@woobling.comE<gt>'
abstract: A Meta Object Protocol for Perl 5
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  B: 0
  Carp: 0
  Scalar::Util: 1.18
  Sub::Name: 0.02
build_requires:
  File::Spec: 0
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  Class::MOP:
    file: lib/Class/MOP.pm
    version: 0.37_002
  Class::MOP::Attribute:
    file: lib/Class/MOP/Attribute.pm
    version: 0.14
  Class::MOP::Class:
    file: lib/Class/MOP/Class.pm
    version: 0.21
  Class::MOP::Immutable:
    file: lib/Class/MOP/Immutable.pm
    version: 0.01
  Class::MOP::Instance:
    file: lib/Class/MOP/Instance.pm
    version: 0.03
  Class::MOP::Method:
    file: lib/Class/MOP/Method.pm
    version: 0.05
  Class::MOP::Method::Accessor:
    file: lib/Class/MOP/Method/Accessor.pm
    version: 0.01
  Class::MOP::Method::Constructor:
    file: lib/Class/MOP/Method/Constructor.pm
    version: 0.01
  Class::MOP::Method::Wrapped:
    file: lib/Class/MOP/Method/Wrapped.pm
    version: 0.02
  Class::MOP::Module:
    file: lib/Class/MOP/Module.pm
    version: 0.02
  Class::MOP::Object:
    file: lib/Class/MOP/Object.pm
    version: 0.02
  Class::MOP::Package:
    file: lib/Class/MOP/Package.pm
    version: 0.05
  metaclass:
    file: lib/metaclass.pm
    version: 0.03
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
