---
name: Class-MOP
version: 0.31
author: ~
abstract: A Meta Object Protocol for Perl 5
license: perl
requires:
  B: 0
  Carp: 0.01
  Scalar::Util: 1.18
  Sub::Name: 0.02
build_requires:
  File::Spec: 0
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  Class::MOP:
    file: lib/Class/MOP.pm
    version: 0.31
  Class::MOP::Attribute:
    file: lib/Class/MOP/Attribute.pm
    version: 0.10
  Class::MOP::Attribute::Accessor:
    file: lib/Class/MOP/Attribute.pm
    version: 0.10
  Class::MOP::Class:
    file: lib/Class/MOP/Class.pm
    version: 0.16
  Class::MOP::Class::Immutable:
    file: lib/Class/MOP/Class/Immutable.pm
    version: 0.01
  Class::MOP::Instance:
    file: lib/Class/MOP/Instance.pm
    version: 0.02
  Class::MOP::Method:
    file: lib/Class/MOP/Method.pm
    version: 0.03
  Class::MOP::Method::Wrapped:
    file: lib/Class/MOP/Method.pm
    version: 0.03
  Class::MOP::Module:
    file: lib/Class/MOP/Module.pm
    version: 0.01
  Class::MOP::Package:
    file: lib/Class/MOP/Package.pm
    version: 0.01
  metaclass:
    file: lib/metaclass.pm
    version: 0.03
generated_by: Module::Build version 0.2611
